version: '3'

services:

  postgresql:
    image: postgres:13
    environment:
      - POSTGRES_DB=db_main
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123
      - DB_CONNECTION=pgsql
      - DB_HOST=postgresql
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "3306:3306"


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  php-fpm:
    build:
      context: docker/php-fpm
    links:
      - postgresql
    depends_on:
      - postgresql
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - .:/var/www

  nginx:
    build:
      context: docker/nginx
    links:
      - postgresql
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"


