version: '3'

services:

  postgresql:
    image: postgres:13
    environment:
      - POSTGRES_DB=db_main
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123
      - DB_CONNECTION=pgsql
      - DB_HOST=postgresql
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "3306:3306"


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  php-fpm:
    build:
      context: ./php-fpm
    links:
      - postgresql
    depends_on:
      - postgresql
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
    volumes:
      - ../payment:/var/www

  nginx:
    build:
      context: ./nginx
    links:
      - postgresql
    volumes:
      - ../payment:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"


